/* AUTO-GENERATED by scripts/ingest-cert-guides.mjs — do not edit by hand.
   Source: cloud-certification-exam-prep (MLA-C01, SAP-C02). Re-run to refresh. */
import type { LearningPath } from './learningPaths';

export const INGESTED_PATHS: LearningPath[] = [
  {
    id: 'mla-c01', certCode: 'MLA-C01', certName: 'AWS Machine Learning Associate',
    tagline: 'Data engineering, model training, deployment and MLOps on Amazon SageMaker — MLA-C01 study path.',
    difficulty: 'Intermediate', totalHours: 10, color: '#01A88D',
    steps: [
      { id: 'mla-m01-notes', type: 'notes', resourceId: 'mla-m01', title: 'Read: Data Engineering', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'mla-m02-notes', type: 'notes', resourceId: 'mla-m02', title: 'Read: Exploratory Data Analysis', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'mla-m03-notes', type: 'notes', resourceId: 'mla-m03', title: 'Read: Machine Learning Implementation and Operations', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'mla-m04-notes', type: 'notes', resourceId: 'mla-m04', title: 'Read: Modeling', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' }
    ],
  },
  {
    id: 'sap-c02', certCode: 'SAP-C02', certName: 'AWS Solutions Architect Professional',
    tagline: 'Sixteen domains — accounts, networking, migrations, disaster recovery, and cost control — for the SAP-C02 professional exam.',
    difficulty: 'Advanced', totalHours: 24, color: '#C925D1',
    steps: [
      { id: 'sap-01-notes', type: 'notes', resourceId: 'sap-01', title: 'Read: Accounts', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-02-notes', type: 'notes', resourceId: 'sap-02', title: 'Read: Identity', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-03-notes', type: 'notes', resourceId: 'sap-03', title: 'Read: Networking', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-04-notes', type: 'notes', resourceId: 'sap-04', title: 'Read: Storage', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-05-notes', type: 'notes', resourceId: 'sap-05', title: 'Read: Compute', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-06-notes', type: 'notes', resourceId: 'sap-06', title: 'Read: Monitoring', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-07-notes', type: 'notes', resourceId: 'sap-07', title: 'Read: Databases', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-08-notes', type: 'notes', resourceId: 'sap-08', title: 'Read: Data Analytics', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-09-notes', type: 'notes', resourceId: 'sap-09', title: 'Read: Containers And Serverless', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-10-notes', type: 'notes', resourceId: 'sap-10', title: 'Read: Caching', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-11-notes', type: 'notes', resourceId: 'sap-11', title: 'Read: Migrations', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-12-notes', type: 'notes', resourceId: 'sap-12', title: 'Read: Security And Config', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-13-notes', type: 'notes', resourceId: 'sap-13', title: 'Read: Disaster Recovery', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-14-notes', type: 'notes', resourceId: 'sap-14', title: 'Read: Iac', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-15-notes', type: 'notes', resourceId: 'sap-15', title: 'Read: Deployment', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' },
      { id: 'sap-16-notes', type: 'notes', resourceId: 'sap-16', title: 'Read: Other', subtitle: '', estimatedMinutes: 12, icon: 'book-open', why: 'Core exam-guide reading.' }
    ],
  },
];
