"""m05-dynamodb-sse ("Amazon DynamoDB SSE example") — recreation.

Canvas 1000x562 (~x0.5 from the 2001x1125 slide). DynamoDB server-side encryption: (1) AWS KMS
generates a table key, (2) DynamoDB generates per-item data encryption keys encrypted with the
table key, (3) KMS uses an AWS KMS key to encrypt the table key. Each table item gets its own
data key (red padlocks); the table key is stored encrypted (purple padlock).
Official DynamoDB / data-table / gear icons; key + padlock glyphs drawn.
"""
from aws_style import Diagram, P

INK = "#232F3E"
BLUE = "#2A6FD6"
BADGE = "#4A148C"
REDLOCK = "#C2185B"
PURPLE = "#7B1FA2"
GRAY = "#8A929B"
DDB = "Arch_Amazon-DynamoDB_48.svg"
TABLE = "Res_Data-Table_48_Light.svg"
GEAR = "Res_Gear_48_Light.svg"

d = Diagram("Amazon DynamoDB SSE example", width=1000, height=562)
d._cell("rule", "rounded=0;html=1;fillColor=#8C4FFF;strokeColor=none;", 38, 78, 620, 4)


def badge(cid, x, y, n):
    d._cell(cid, f"ellipse;html=1;fillColor={BADGE};strokeColor=none;fontColor=#FFFFFF;"
            "fontStyle=1;fontSize=15;fontFamily=Amazon Ember;align=center;verticalAlign=middle;",
            x, y, 32, 32, n)


def line(cid, pts, color=INK, w=2, head="block"):
    mid = "".join(f'<mxPoint x="{x}" y="{y}"/>' for x, y in pts[1:-1])
    d.cells.append(
        f'<mxCell id="{cid}" style="endArrow={head};endSize=6;startArrow=none;html=1;rounded=0;'
        f'strokeColor={color};strokeWidth={w};" edge="1" parent="1">'
        f'<mxGeometry relative="1" as="geometry"><mxPoint x="{pts[0][0]}" y="{pts[0][1]}" as="sourcePoint"/>'
        f'<mxPoint x="{pts[-1][0]}" y="{pts[-1][1]}" as="targetPoint"/>'
        f'<Array as="points">{mid}</Array></mxGeometry></mxCell>')


def padlock(cid, x, y, color, s=20):
    d._cell(cid + "b", f"rounded=1;arcSize=22;html=1;fillColor={color};strokeColor=none;", x, y + s * 0.45, s, s * 0.6)
    d._cell(cid + "s", "shape=mxgraph.basic.half_circle;direction=north;html=1;fillColor=none;"
            f"strokeColor={color};strokeWidth=3;", x + s * 0.2, y, s * 0.6, s * 0.6)


def key_glyph(cid, x, y, color):
    d._cell(cid + "r", f"ellipse;html=1;fillColor=none;strokeColor={color};strokeWidth=4;", x, y + 4, 16, 16)
    d._cell(cid + "s", f"rounded=0;html=1;fillColor={color};strokeColor=none;", x + 14, y + 10, 22, 4)
    d._cell(cid + "t1", f"rounded=0;html=1;fillColor={color};strokeColor=none;", x + 30, y + 14, 4, 8)


# ---- Amazon DynamoDB --------------------------------------------------------
d.svg_icon("ddb", 130, 150, 52, 52, DDB, "")
d.text(98, 210, 120, 48, "Amazon\nDynamoDB", size=16, align="center")

# ---- encryption algorithm + table key --------------------------------------
d.text(420, 110, 220, 48, "DynamoDB\nencryption algorithm", size=16, align="center")
d.svg_icon("algo", 488, 168, 48, 48, GEAR, "")
d.svg_icon("tkey", 470, 220, 48, 48, GEAR, "")
d.text(556, 232, 130, 24, "Table key", size=16, align="left")
line("algo_down", [(512, 160), (512, 168)], head="none")

# ---- AWS KMS + KMS key ------------------------------------------------------
key_glyph("kms", 856, 180, GRAY)
d.text(826, 232, 130, 24, "AWS KMS", size=16, align="center")
badge("b1", 588, 116, "1")
d.text(626, 108, 240, 48, "A table key is generated by\nAWS KMS.", size=16, align="left")
d.text(836, 296, 160, 24, "AWS KMS Key", size=16, align="left")
badge("b3", 648, 354, "3")
d.text(688, 350, 240, 48, "KMS uses an AWS KMS Key\nto encrypt the table key.", size=16, align="left")

# ---- step 2 + table ---------------------------------------------------------
badge("b2", 138, 350, "2")
d.text(36, 392, 260, 70, "Data encryption keys\ngenerated by DynamoDB and\nencrypted with table key.", size=16, align="left")
d.svg_icon("table", 138, 442, 52, 52, TABLE, "")
d.text(196, 470, 90, 24, "Table", size=16, bold=True, align="left")

# table items + per-item data-key padlocks
d._cell("tzone", "rounded=1;arcSize=4;html=1;fillColor=none;strokeColor=#2A6FD6;strokeWidth=1.5;"
        "dashed=1;dashPattern=4 3;", 296, 442, 600, 96)
items = [(330, 320, "Item 1"), (412, 350, "Item 2, 3"), (494, 320, "Item 4"), (576, 350, "Item 5-7")]
for cid, (cx, ly, label) in zip(["i0", "i1", "i2", "i3"], items):
    padlock(cid, cx - 10, ly, REDLOCK)
    line(cid + "arr", [(cx, ly + 22), (cx, 478)])
    d.text(cx - 50, 482, 100, 24, label, size=15, align="center")
padlock("tkstore", 692, 458, PURPLE)

# ---- main flow arrows -------------------------------------------------------
line("ddb_top", [(182, 176), (560, 176), (560, 168)], head="none")   # DynamoDB -> algorithm region
line("tkey_kms", [(518, 244), (854, 244)], head="block")             # table key -> AWS KMS (1)
line("kms_store", [(880, 256), (880, 360), (820, 360)], head="none") # KMS key path
line("store_table", [(648, 360), (648, 490), (300, 490)], head="block")  # encrypted table key -> table
line("ddb_table", [(156, 202), (156, 442)], head="block")            # DynamoDB -> table

res = d.save("m05-dynamodb-sse")
print("built:", res.get("src"))
from aws_style import compare
print("cmp  :", compare("m05-dynamodb-sse"))
